# Generated by Django 5.0 on 2023-12-12 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="performance",
            old_name="play",
            new_name="plays",
        ),
    ]
