# Generated by Django 5.0 on 2023-12-12 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0002_rename_play_performance_plays"),
    ]

    operations = [
        migrations.RenameField(
            model_name="performance",
            old_name="plays",
            new_name="play",
        ),
    ]
