# Generated by Django 5.0 on 2023-12-12 16:02

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0004_alter_ticket_performance_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.play_image_file_path
            ),
        ),
    ]
