# Generated by Django 5.0 on 2023-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0007_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="actor",
            unique_together={("first_name", "last_name")},
        ),
    ]
