# Generated by Django 5.0 on 2023-12-12 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0008_alter_genre_name_alter_actor_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
