# Generated by Django 5.0 on 2023-12-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0009_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="actor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("performance", "row", "seat"), name="unique_ticket_seat"
            ),
        ),
    ]
