# Generated by Django 5.0 on 2023-12-12 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0011_remove_ticket_unique_ticket_seat_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row", "seat")},
        ),
    ]
